MESSAGES = {
    "USER_REGISTER_SUCCESS": "User registered successfully",
    "VALIDATION_FAILED": "Validation failed",
    "OTP_SEND":"An OTP has been sent to your email. Please check your inbox.",
    "OTP_REQUIRED":"OTP and OTP Type are required",
    "OTP_VERIFICATION_ERROR":"OTP is invalid",
    "USER_REGISTRATION_ERROR": "An error occurred while registering the user",
    "USER_UPDATE_SUCCESS": "User updated successfully",
    "USER_NOT_FOUND": "User with the provided ID does not exist.",
    "LOGIN_SUCCESS": "Login successful",
    "EMAIL_NOT_VERIFIED": "Your email was not verified, Please check your inbox.",
    "INVALID_CREDENTIALS": "Invalid credentials",
    "OTP_RESENT_SUCCESS": "Otp was successfully sent to your email",
    "ACCOUNT_INACTIVE":"Account is inactive please contact your administrator",
    "SUPER_ADMIN_LOGIN_DENIED": "Super admin user is not allowed to login here.",
    "SUPER_ADMIN_LOGIN_SUCCESS": "Super admin user is login succcessful.",
    "OTP_RESEND_ERROR" : "Error in sending OTP",
    "ONLY_SUPER_ADMIN_ALLOWED": "Only Super admin user is allowed to login here.",
    "OTP_SENT_SUCCESS": "OTP sent to your email",
    "PROCESSING_REQUEST_ERROR": "An error occurred while processing the request",
    "OTP_VERIFIED_SUCCESS": "OTP verified successfully",
    "INVALID_OTP": "Invalid OTP. Please check and try again.",
    "PASSWORD_RESET_SUCCESS": "Password reset successfully.",
    "ROLES_RETRIEVED_SUCCESS": "Roles retrieved successfully.",
    "NO_ROLES_FOUND": "No roles found.",
    "ROLES_RETRIEVAL_ERROR": "An error occurred while retrieving roles.",
    # OTP Verification Messages
    "OTP_SENT_SUCCESS": "OTP sent to the email successfully.",
    "OTP_ERROR": "An error occurred while sending OTP.",
    # User Profile Fetching Messages
    "USER_PROFILE_FETCH_SUCCESS": "User profile fetched successfully.",
    "USER_PROFILE_FETCH_ERROR": "An error occurred while fetching user profile.",
    "COMMUNUTY_FETCH_SUCCESS": "Communities fetched successfully.",
    "COMMUNITY_SAVE_SUCCESS": "Community information saved successfully.",
    "INVALID_DATA": "Invalid data. Please check the input fields and try again.",
    "COMMUNITY_SAVE_ERROR": "An error occurred while saving community information.",
    "COMMUNITY_UPDATE_SUCCESS": "Community information updated successfully.",
    "COMMUNITY_UPDATE_ERROR": "An error occurred while updating community information.",
    "COMMUNITY_NOT_FOUND": "Community not found.",
    "LOCATION_NOT_FOUND": "Location not found.",
    "COMMUNITY_DELETE_SUCCESS": "Community and related documents deleted successfully.",
    "COMMUNITY_DELETE_ERROR": "An error occurred while deleting community information.",
    "NO_COMMUNITIES_FOUND": "No communities found for the given filters.",
    "COMMUNITIES_FETCH_SUCCESS": "Communities fetched successfully.",
    "COMMUNITY_FETCH_SUCCESS": "Community information fetched successfully.",
    "COMMUNITY_FETCH_ERROR": "An error occurred while fetching community information.",
    "DOCS_RETRIEVED_SUCCESS": "Documents retrieved successfully.",
    "NO_DOCS_FOUND": "No documents found.",
    "DOCS_RETRIEVAL_ERROR": "An error occurred while retrieving documents.",
    "COMMUNITY_NAME_OR_CITY_REQUIRED": "At least one field is required: community_name or community_city",
    "COMMUNITY_FOUND": "Community found matching the filters.",
    "COMMUNITY_CREATE_SUCCESS": "Community successfully created.",
    "COMMUNITY_CREATE_API_ERROR": "An error occurred while calling the external API to create the community.",
    "VENDOR_DATA_EXISTS": "Data already exists for this city.",
    "EXTERNAL_API_ERROR": "External API error.",
    "INVALID_JSON_RESPONSE": "Invalid JSON response from external API.",
    "VENDOR_DETAILS_PROCESSED": "Vendor details and vendor types processed successfully.",
    "EXTERNAL_API_CALL_ERROR": "An error occurred while calling the external API.",
    "DOCUMENT_FETCH_SUCCESS": "Documents fetched successfully.",
    "DOCUMENT_FETCH_ERROR": "Error fetching documents.",
    "DOCUMENT_CREATED_SUCCESS": "Document created successfully.",
    "DOCUMENT_CREATION_ERROR": "An error occurred while creating the document.",
    "DOCUMENT_DELETED_SUCCESS": "Document deleted successfully.",
    "DOCUMENT_NOT_FOUND": "Document not found.",
    "DOCUMENT_UPDATED_SUCCESS": "Document updated successfully.",
    "INVALID_DATA": "Invalid data provided.",
    "DOCUMENT_UPDATE_ERROR": "Error updating the document.",
    "DOC_TYPES_FETCH_SUCCESS": "Document types fetched successfully.",
    "DOC_TYPES_FETCH_ERROR": "An error occurred while fetching document types.",
    "DOCUMENT_FETCH_SUCCESS": "Document fetched successfully.",
    "DOCUMENT_FETCH_ERROR": "An error occurred while fetching the document.",
    "SUCCESS_CREATE": "Claim request successfully created.",
    "ERROR_USER_NOT_FOUND": "User not found.",
    "ERROR_COMMUNITY_NOT_FOUND": "Community not found.",
    "ERROR_CLAIM_EXISTS": "Claim request already exists.",
    "ERROR_GENERAL": "Something went wrong.",
    "SUCCESS_STATUS_UPDATE": "Status updated successfully.",
    "ERROR_CLAIM_NOT_FOUND": "Claim request not found.",
    "SUCCESS_FETCH": "Data fetched successfully.",
    "SUCCESS_FETCH_HOMEOWNERS": "All home owners fetched successfully.",
    "SUCCESS_ASSIGN_USER": "User assigned to community successfully.",
    "ERROR_USER_ALREADY_ASSIGNED": "User is already assigned to this community.",
    "SUCCESS_FETCH_USER_DETAILS": "User details fetched successfully.",
    "ERROR_INVALID_SERIALIZER": "Invalid serializer data.",
    "SUCCESS_USER_REMOVED": "User has removed from the community",
    "API_CALL_ERROR": "An error occurred while calling the external API.",
    "NO_COMMUNITIES_ASSIGNED": "No communities assigned to this user.",
    "COMMUNITIES_FETCHED_SUCCESSFULLY": "Communities fetched successfully.",
    "INVALID_INPUT_DATA": "Invalid input data.",
    "UNEXPECTED_ERROR": "An unexpected error occurred.",
    "ALL_PROVIDERS": "Providers fetched successfully."
}
